// This file is automatically generated. Do not modify it manually.
// You can publish a new version of this file by running `npx firebase-frameworks-tools client:web --config=.firebase/hosting.json --out src/firebase/config.ts`

export const firebaseConfig = {
  "projectId": "studio-7771091082-4e1c2",
  "appId": "1:928535696937:web:10e30e89ea7e2732ab2e38",
  "apiKey": "AIzaSyC99LWCujJl4AXlKRBXZ27l9WVvKoCrAU0",
  "authDomain": "studio-7771091082-4e1c2.firebaseapp.com",
  "storageBucket": "studio-7771091082-4e1c2.appspot.com",
  "messagingSenderId": "928535696937",
  "measurementId": "G-L0V30018E5"
};

// export const firebaseConfig = {
//   apiKey: "AIzaSyDON1hOAarZv-d0ckI7OCMG2JJYHC9bvtI",
//   authDomain: "hashmi-vip-numbers.firebaseapp.com",
//   projectId: "hashmi-vip-numbers",
//   storageBucket: "hashmi-vip-numbers.firebasestorage.app",
//   messagingSenderId: "501716649750",
//   appId: "1:501716649750:web:709b57cc930fa6bb84f237",
//   measurementId: "G-KQE43JR8WE"
// };